# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://shdfe.github.io/mlh-hackathon-boilerplate/"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "AltoHacks | 5/6 February 2022"
  description: "Official website for AltoHacks."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "AltoHacks"
  description: "description"
  date:        "<Create date>"
  location:    "<Online, add zoom later>"

  trust_badge:
    year:   "2020"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "OQLIH21AlhceWCqeSErY0cCpXqEMlqH2XyX1j5co9oo"
          redirect_uri: "https://shdfe.github.io/mlh-hackathon-boilerplate/"
      - text: "Sponsor"
        href: "mailto:altohackinfo@gmail.com"

  about:
    description: >
      Example Hacks is a hackathon hosted at <online>.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at [insert venue location here].
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
